# Generated by Django 5.1.7 on 2025-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_default='', max_length=255, verbose_name='username'),
        ),
    ]
