# Generated by Django 5.1.7 on 2025-03-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumSong',
        ),
    ]
