# Generated by Django 5.1.7 on 2025-03-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_delete_albumsong'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
