# Generated by Django 5.1.7 on 2025-05-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
